name: Run

on:
  schedule:
    - cron: "0 6-22 * * *"    # Run zu jeder vollen Stunde von 6 bis 22 Uhr
  workflow_dispatch:       # Run manuell ausgelöst

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Repo auschecken
      - name: Checkout repository
        uses: actions/checkout@v4

      # Python-Version auswählen
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Dependencies installieren (falls Datei vorhanden)
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Lade Konfiguration
      - name: Write secret students configuration to JSON file
        run: |
          echo "${CONFIG_JSON}" > students.json
        env:
          CONFIG_JSON: ${{ secrets.STUDENTS }}

      # Laden der bereits bekannten Vertretungen 
      # aus dem vorhergehenden Run, zur Vermeidung doppelter Benachrichtigungen
      - name: Load cached state
        uses: actions/cache@v4
        with:
          path: .state/
          key: substitutionsCache-${{ github.run_id }}
          restore-keys: |
              substitutionsCache-

      #- name: Debug list cache
      #  run: ls -l .state/knownSubstitutions.txt

      #- name: Debug cat cache
      #  run: cat .state/knownSubstitutions.txt

      # Erstelle .state Verzeichnis, falls es noch nicht existiert
      - name: Ensure state exists
        run: mkdir -p .state

      - name: Debug list cache 2
        run: ls -l .state/

      #- name: Debug cat cache 2
      #  run: cat .state/*

      # Python Script ausführen
      - name: Run Python script
        env:
          EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
          EMAIL_SMTP_SERVER: ${{ secrets.EMAIL_SMTP_SERVER }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        run: python main.py

      - name: Debug list cache 3
        run: ls -l .state/knownSubstitutions.txt

      - name: Debug cat cache 3
        run: cat .state/knownSubstitutions.txt

      # Zwischenspeichern der bereits bekannten Vertretungen 
      # für den nächsten Run, zur Vermeidung doppelter Benachrichtigungen
      - name: Save state to cache
        uses: actions/cache/save@v4
        with:
          path: .state/
          key: substitutionsCache-${{ github.run_id }}
